FROM php:5-cli

RUN apt-get update && apt-get install -y mysql-client postgresql postgresql-contrib
RUN docker-php-ext-install -j$(nproc) mysqli

RUN curl -sS https://silverstripe.github.io/sspak/install | php -- /usr/local/bin

RUN usermod -u 1000 www-data && \
	usermod -G staff www-data

VOLUME ["/app"]
WORKDIR /app

CMD ["-"]
ENTRYPOINT ["/usr/local/bin/sspak"]
